### ISSUE TITLE
This is a client, can we write some server for ios?

### ISSUE THREAD

**Issue by ssaguiar** [kpavankotesh/simple-tcp-client-app#1]
Your code is very good but I wish to know if there is some way to write a http server to use inside an application, wich will work at the address of 127.0.0.1.

I aplogise to post this in Issues, but could not find a place to ask questions.

**Comment by kpavankotesh** [comment]
[This link](https://stackoverflow.com/questions/3132105/how-do-you-access-a-website-running-on-localhost-from-iphone-browser) has some references to access localhost on browser. Not sure if this works fine inside the application. You'll have to try it yourself.
